### ISSUE TITLE
Model lookup from repositories no longer works with version 3.8.0

### ISSUE THREAD

**Issue by mwa** [claeis/ili2db#76] opened 2017-04-12 09:54 UTC
The model lookup from remote repositories fails when doing a schema import. The class `ch.ehi.iox.ilisite.ILIREPOSITORY09` seems to be missing.

Example schema import of model https://models.geo.admin.ch/BAFU/KbS_V1_3.ili:
```
$ java -Xmx256m -jar /work/libs/ili2pg/ili2pg.jar --dbport 5432 --dbdatabase testdb --dbschema kbs --dbusr '***' --dbpwd '***' --schemaimport --trace /tmp/KbS_V1_3.ili

Info: dburl <jdbc:postgresql:wfs_agg>
Info: dbusr <dev>
Info: ili2pg-3.8.0-20170410
Info: ili2c-4.7.1-20170410
Info: iox-ili-1.17.0-master-20170410
Info: java.version 1.8.0_121
Info: user.name <mwa>
Info: maxMemory 233472 KB
Info: dbschema <debug_kbs>
Info: dburl <jdbc:postgresql:wfs_agg>
Info: dbusr <dev>
Info: databaseProduct <PostgreSQL>
Info: databaseVersion <9.5.6>
Info: driverName <PostgreSQL Native Driver>
Info: driverVersion <PostgreSQL 9.4.1208.jre6>
Info: postGISVersion <POSTGIS="2.2.1 r14555" GEOS="3.5.1-CAPI-1.9.1 r4246" PROJ="Rel. 4.9.2, 08 September 2015" GDAL="GDAL 2.1.3, released 2017/20/01" LIBXML="2.9.3" LIBJSON="0.11.99" RASTER>
Info: compile models...
Info: getModelRepos(): pathmap key <%ILI_FROM_DB> (Main.java:753)
Info: getModelRepos(): pathmap key <%XTF_DIR> (Main.java:753)
Info: getModelRepos(): pathmap key <%JAR_DIR> (Main.java:753)
Info: setRepositories(): uri </tmp> (IliManager.java:87)
Info: setRepositories(): uri <http://models.interlis.ch/> (IliManager.java:87)
Info: setRepositories(): uri </work/libs/ili2pg> (IliManager.java:87)
Info: lookup model <LocalisationCH_V1> 2.3 in repository </tmp>
Info: getIliFiles(): scan ili-files in folder </tmp>... (RepositoryAccess.java:94)
Info: lookup model <LocalisationCH_V1> 2.3 in repository <http://models.interlis.ch/>
Info: getIliFiles(): read ilimodels.xml from <http://models.interlis.ch/>... (RepositoryAccess.java:108)
Exception in thread "main" java.lang.NoClassDefFoundError: ch/ehi/iox/ilisite/ILIREPOSITORY09
        at ch.interlis.ilirepository.impl.RepositoryAccess.readIliModelsXml(RepositoryAccess.java:295)
        at ch.interlis.ilirepository.impl.RepositoryAccess.readIliModelsXml(RepositoryAccess.java:283)
        at ch.interlis.ilirepository.impl.RepositoryAccess.getIliFiles(RepositoryAccess.java:109)
        at ch.interlis.ilirepository.impl.RepositoryCrawler.getIliFileMetadataShallow(RepositoryCrawler.java:178)
        at ch.interlis.ilirepository.impl.RepositoryCrawler.getIliFileMetadataDeep(RepositoryCrawler.java:100)
        at ch.interlis.ilirepository.IliManager.createConfig(IliManager.java:358)
        at ch.interlis.ilirepository.IliManager.getConfigWithFiles(IliManager.java:252)
        at ch.interlis.ili2c.Main.runCompiler(Main.java:487)
        at ch.ehi.ili2db.base.Ili2db.runSchemaImport(Unknown Source)
        at ch.ehi.ili2db.base.Ili2db.run(Unknown Source)
        at ch.ehi.ili2db.AbstractMain.domain(Unknown Source)
        at ch.ehi.ili2pg.PgMain.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: ch.ehi.iox.ilisite.ILIREPOSITORY09
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 12 more
```

The schema import works though after manually copying all dependent models into the local model dir.

**Comment by edigonzales** [comment] 2017-04-12 10:09
Reminds me of this: [https://github.com/claeis/iox-ili/issues/5](https://github.com/claeis/iox-ili/issues/5)

**Comment by aweb777** [comment] 2017-04-17 07:01
having a similar probrem 
when running: 
"java -jar ili2pg.jar --schemaimport --dbhost localhost --dbdatabase dbnpl2317 --dbschema npl23 --createEnumTabs --createGeomIdx --defaultSrsCode 2056 --dbusr postgres --dbpwd 4654 --log imp2_npl2317_171.log SO_Nutzungsplanung_20170105.ili"

procedure stops and the log looks like that: 
"Info: ili2pg-3.8.0-20170410
Info: ili2c-4.7.1-20170410
Info: iox-ili-1.17.0-master-20170410
Info: java.version 1.8.0_121
Info: user.name <Armin Weber>
Info: maxMemory 253440 KB
Info: dbschema <npl23>
Info: dburl <jdbc:postgresql://localhost/dbnpl2317>
Info: dbusr <postgres>
Info: databaseProduct <PostgreSQL>
Info: databaseVersion <9.5.1>
Info: driverName <PostgreSQL Native Driver>
Info: driverVersion <PostgreSQL 9.4.1208.jre6>
Info: postGISVersion <POSTGIS="2.3.1 r15264" GEOS="3.6.0-CAPI-1.10.0 r4265" SFCGAL="1.3.0" PROJ="Rel. 4.9.1, 04 March 2015" GDAL="GDAL 2.1.1, released 2016/07/07" LIBXML="2.7.8" LIBJSON="0.12" TOPOLOGY RASTER>
Info: compile models...
Info: lookup model <GeometryCHLV95_V1> 2.3 in repository <D:\Daten\Qgis\npl2317>
Info: lookup model <GeometryCHLV95_V1> 2.3 in repository <http://models.interlis.ch/>"

the command line window looks like that:
"D:\Daten\Qgis\npl2317>java -jar ili2pg.jar --schemaimport --dbhost localhost --d
bdatabase dbnpl2317 --dbschema npl23 --createEnumTabs --createGeomIdx --defaultS
rsCode 2056 --dbusr postgres --dbpwd 4654 --log imp2_npl2317_171.log SO_Nutzungs
planung_20170105.ili
Info: dburl <jdbc:postgresql://localhost/dbnpl2317>
Info: dbusr <postgres>
Info: ili2pg-3.8.0-20170410
Info: ili2c-4.7.1-20170410
Info: iox-ili-1.17.0-master-20170410
Info: java.version 1.8.0_121
Info: user.name <Armin Weber>
Info: maxMemory 253440 KB
Info: dbschema <npl23>
Info: dburl <jdbc:postgresql://localhost/dbnpl2317>
Info: dbusr <postgres>
Info: databaseProduct <PostgreSQL>
Info: databaseVersion <9.5.1>
Info: driverName <PostgreSQL Native Driver>
Info: driverVersion <PostgreSQL 9.4.1208.jre6>
Info: postGISVersion <POSTGIS="2.3.1 r15264" GEOS="3.6.0-CAPI-1.10.0 r4265" SFCG
AL="1.3.0" PROJ="Rel. 4.9.1, 04 March 2015" GDAL="GDAL 2.1.1, released 2016/07/0
7" LIBXML="2.7.8" LIBJSON="0.12" TOPOLOGY RASTER>
Info: compile models...
Info: lookup model <GeometryCHLV95_V1> 2.3 in repository <D:\Daten\Qgis\npl2317>

Info: lookup model <GeometryCHLV95_V1> 2.3 in repository <http://models.interlis
.ch/>
Exception in thread "main" java.lang.NoClassDefFoundError: ch/ehi/iox/ilisite/IL
IREPOSITORY09
        at ch.interlis.ilirepository.impl.RepositoryAccess.readIliModelsXml(Repo
sitoryAccess.java:295)
        at ch.interlis.ilirepository.impl.RepositoryAccess.readIliModelsXml(Repo
sitoryAccess.java:283)
        at ch.interlis.ilirepository.impl.RepositoryAccess.getIliFiles(Repositor
yAccess.java:109)
        at ch.interlis.ilirepository.impl.RepositoryCrawler.getIliFileMetadataSh
allow(RepositoryCrawler.java:178)
        at ch.interlis.ilirepository.impl.RepositoryCrawler.getIliFileMetadataDe
ep(RepositoryCrawler.java:100)
        at ch.interlis.ilirepository.IliManager.createConfig(IliManager.java:358
)
        at ch.interlis.ilirepository.IliManager.getConfigWithFiles(IliManager.ja
va:252)
        at ch.interlis.ili2c.Main.runCompiler(Main.java:487)
        at ch.ehi.ili2db.base.Ili2db.runSchemaImport(Unknown Source)
        at ch.ehi.ili2db.base.Ili2db.run(Unknown Source)
        at ch.ehi.ili2db.AbstractMain.domain(Unknown Source)
        at ch.ehi.ili2pg.PgMain.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: ch.ehi.iox.ilisite.ILIREPOSITORY09
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 12 more

D:\Daten\Qgis\npl2317>pause
Drücken Sie eine beliebige Taste . . ."

**Comment by aweb777** [comment] 2017-04-17 07:07
just found ili2pg-3.5.0.zip, works fine

**Comment by edigonzales** [comment] 2017-04-17 07:30
This is fixed with [https://github.com/claeis/iox-ili/commit/7bf723983c40fcc0e2cfc2a9bc93ebdd9bfa3e65](https://github.com/claeis/iox-ili/commit/7bf723983c40fcc0e2cfc2a9bc93ebdd9bfa3e65).

**Comment by aweb777** [comment] 2017-04-17 07:37
Hello Stefan, i still enconter prblems with 3.5.0. 
Does your remark above lead to a ili2pg-3.x.0.zip?

**Comment by edigonzales** [comment] 2017-04-17 07:39
Same error with 3.5.0? `--trace`?

**Comment by aweb777** [comment] 2017-04-17 07:39
just  a second

**Comment by aweb777** [comment] 2017-04-17 07:41
am i exchanging the version correctly by replacing ili2pg.jar and libs?

**Comment by edigonzales** [comment] 2017-04-17 07:42
Don't exchange anything. Just unzip an older version:

/Users/stefan/apps/ili2pg-3.5.0/...
/Users/stefan/apps/ili2pg-3.6.1/...
/Users/stefan/apps/ili2pg-3.8.0/...

**Comment by aweb777** [comment] 2017-04-17 07:47
3.5.0 
Creation OK
java -jar ili2pg.jar --schemaimport --dbhost localhost --dbdatabase dbnpl2317 --dbschema npl23 --createEnumTabs --createGeomIdx --defaultSrsCode 2056 --dbusr postgres --dbpwd 4654 --log imp2_npl2317_190.log SO_Nutzungsplanung_20170105.ili
pause
Info: ili2pg-3.5.0-20161125
Info: ili2c-4.5.23-20160708
Info: java.version 1.8.0_121
Info: user.name <Armin Weber>
Info: maxMemory 253440 KB
Info: dbschema <npl23>
Info: dburl <jdbc:postgresql://localhost/dbnpl2317>
Info: dbusr <postgres>
Info: databaseProduct <PostgreSQL>
Info: databaseVersion <9.5.1>
Info: driverVersion <PostgreSQL 9.4.1208.jre6>
Info: postGISVersion <POSTGIS="2.3.1 r15264" GEOS="3.6.0-CAPI-1.10.0 r4265" SFCGAL="1.3.0" PROJ="Rel. 4.9.1, 04 March 2015" GDAL="GDAL 2.1.1, released 2016/07/07" LIBXML="2.7.8" LIBJSON="0.12" TOPOLOGY RASTER>
Info: compile models...
Info: lookup model <GeometryCHLV95_V1> 2.3 in repository <D:\Daten\Qgis\npl2317>
Info: lookup model <GeometryCHLV95_V1> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <GeometryCHLV95_V1> 2.3 in repository <http://models.geo.admin.ch>
Info: lookup model <CHAdminCodes_V1> 2.3 in repository <D:\Daten\Qgis\npl2317>
Info: lookup model <CHAdminCodes_V1> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <CHAdminCodes_V1> 2.3 in repository <http://models.geo.admin.ch>
Info: lookup model <CoordSys> 2.3 in repository <D:\Daten\Qgis\npl2317>
Info: lookup model <CoordSys> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <Units> 2.3 in repository <D:\Daten\Qgis\npl2317>
Info: lookup model <Units> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <InternationalCodes_V1> 2.3 in repository <D:\Daten\Qgis\npl2317>
Info: lookup model <InternationalCodes_V1> 2.3 in repository <http://models.interlis.ch/>
Info: lookup model <InternationalCodes_V1> 2.3 in repository <http://models.geo.admin.ch>
Info: ilifile <C:\Users\Armin Weber\.ilicache\models.interlis.ch\refhb23\CoordSys-20151124.ili>
Info: ilifile <C:\Users\Armin Weber\.ilicache\models.geo.admin.ch\CH\CHBase_Part2_LOCALISATION_20110830.ili>
Info: ilifile <C:\Users\Armin Weber\.ilicache\models.interlis.ch\refhb23\Units-20120220.ili>
Info: ilifile <C:\Users\Armin Weber\.ilicache\models.geo.admin.ch\CH\CHBase_Part4_ADMINISTRATIVEUNITS_20110830.ili>
Info: ilifile <C:\Users\Armin Weber\.ilicache\models.geo.admin.ch\CH\CHBase_Part1_GEOMETRY_20110830.ili>
Info: ilifile <SO_Nutzungsplanung_20170105.ili>
Info: create table structure...
Info: ...done
Import error
java -jar ili2pg.jar --import --deleteData --dbdatabase dbnpl2317 --dbschema npl23 --createGeomIdx --defaultSrsCode 2056 --dbusr postgres --dbpwd 4654 --log imp5_npl2317_localhost_226.log exp_npl2317_localhost_32.xtf

Info: ili2pg-3.5.0-20161125
Info: ili2c-4.5.23-20160708
Info: java.version 1.8.0_121
Info: user.name <Armin Weber>
Info: maxMemory 253440 KB
Info: dbschema <npl23>
Info: dburl <jdbc:postgresql:dbnpl2317>
Info: dbusr <postgres>
Info: databaseProduct <PostgreSQL>
Info: databaseVersion <9.5.1>
Info: driverVersion <PostgreSQL 9.4.1208.jre6>
Info: postGISVersion <POSTGIS="2.3.1 r15264" GEOS="3.6.0-CAPI-1.10.0 r4265" SFCGAL="1.3.0" PROJ="Rel. 4.9.1, 04 March 2015" GDAL="GDAL 2.1.1, released 2016/07/07" LIBXML="2.7.8" LIBJSON="0.12" TOPOLOGY RASTER>
Info: compile models...
Info: lookup model <SO_Nutzungsplanung_20170105> in repository <jdbc:postgresql:dbnpl2317/npl23>
Info: lookup model <GeometryCHLV95_V1> 2.3 in repository <jdbc:postgresql:dbnpl2317/npl23>
Info: lookup model <CHAdminCodes_V1> 2.3 in repository <jdbc:postgresql:dbnpl2317/npl23>
Info: lookup model <CoordSys> 2.3 in repository <jdbc:postgresql:dbnpl2317/npl23>
Info: lookup model <Units> 2.3 in repository <jdbc:postgresql:dbnpl2317/npl23>
Info: lookup model <InternationalCodes_V1> 2.3 in repository <jdbc:postgresql:dbnpl2317/npl23>
Info: ilifile <C:\Users\Armin Weber\.ilicache\jdbc&003apostgresql&003adbnpl2317\npl23\Units-20120220.ili>
Info: ilifile <C:\Users\Armin Weber\.ilicache\jdbc&003apostgresql&003adbnpl2317\npl23\CHBase_Part2_LOCALISATION_20110830.ili>
Info: ilifile <C:\Users\Armin Weber\.ilicache\jdbc&003apostgresql&003adbnpl2317\npl23\CoordSys-20151124.ili>
Info: ilifile <C:\Users\Armin Weber\.ilicache\jdbc&003apostgresql&003adbnpl2317\npl23\CHBase_Part4_ADMINISTRATIVEUNITS_20110830.ili>
Info: ilifile <C:\Users\Armin Weber\.ilicache\jdbc&003apostgresql&003adbnpl2317\npl23\CHBase_Part1_GEOMETRY_20110830.ili>
Info: ilifile <C:\Users\Armin Weber\.ilicache\jdbc&003apostgresql&003adbnpl2317\npl23\SO_Nutzungsplanung_20170105.ili>
Error: failed to create sequence npl23.t_ili2db_seq
Error:   FEHLER: Relation „t_ili2db_seq“ existiert bereits
Info: create table structure...
Info: delete existing data...
Error: java.io.IOException: failed to check if table npl23.typ_ueberlagernd_flaeche_typ_kt exists
Error:   failed to check if table npl23.typ_ueberlagernd_flaeche_typ_kt exists
Error:     FEHLER: aktuelle Transaktion wurde abgebrochen, Befehle werden bis zum Ende der Transaktion ignoriert

**Comment by edigonzales** [comment] 2017-04-17 07:51
Try e.g. [3.6.1](http://www.eisenhutinformatik.ch/interlis/ili2pg/ili2pg-3.6.1.zip)

Open another issue if it still persists.

**Comment by aweb777** [comment] 2017-04-17 08:01
3.6.1 creation of sceme ok, import ok, qgis doesnt show the tables anymore... what the heck

**Comment by edigonzales** [comment] 2017-04-17 08:15
Works for me:

`java -jar /home/stefan/Apps/ili2pg-3.6.1/ili2pg.jar --dbhost localhost --dbdatabase xanadu2 --dbusr stefan --dbpwd ziegler12 --createEnumTabs --createGeomIdx --disableValidation --defaultSrsCode 2056 --models SO_Nutzungsplanung_20170105 --dbschema npl23 --schemaimport`

`java -jar /home/stefan/Apps/ili2pg-3.6.1/ili2pg.jar --dbhost localhost --dbdatabase xanadu2 --dbusr stefan --dbpwd ziegler12 --createEnumTabs --createGeomIdx --disableValidation --defaultSrsCode 2056 --models SO_Nutzungsplanung_20170105 --dbschema npl23 --import expnpl2317_20170413R.xtf`

**Comment by aweb777** [comment] 2017-04-17 09:10
Thank you, meanwhile they show with QGIS, in qgs the srid was 21781...

**Closed** 2017-04-21 13:16 UTC
