### ISSUE TITLE
ili2pg: Unknown Referenced Object Errors

### ISSUE THREAD

**Issue by frantsch** [claeis/ili2db#93] opened 2017-06-13 10:38 UTC
Using ilivalidator 1.2.1 we validate _Nutzungsplanung_V1_1.xtf_ (data model _Nutzungsplanung_V1_1_). We hereby obtain _"no errors found"_.

Importing this file using ili2pg gives us:

> Error: unknown referenced object Nutzungsplanung_LV95_V1_1.Rechtsvorschriften.Dokument TID x4501_9552_besch referenced from Nutzungsplanung_LV95_V1_1.Geobasisdaten.Typ_Dokument TID x3_nokogde:x4501_9552_besch

Download data and log files (zip) from: `ftp://ohwagaev:ufahnoe1@ftp1.tg.ch`

We were so far not able to pin down the very problem (Data error or ili2pg bug). Any ideas?

**Comment by claeis** [comment] 2017-06-16 15:09
first import the missing object with the mentioned TID

**Comment by claeis** [comment] 2017-08-18 16:23
duplicate of #105

**Closed by claeis** 2017-08-18 16:23 UTC
